### ISSUE TITLE
torchgating command unable run without CUDA even when --cpu specified

### ISSUE THREAD

**Issue by tpoindex** [nuniz/TorchSpectralGating#1]
When trying to run 'torchgating' on an x86 MacOS, an assertion is thrown with or without the --cpu flag.  

```
torchgating sample.wav --graph
...
File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

```

with --cpu:

```
torchgating sample.wav --graph --cpu
...
 File "/usr/local/lib/python3.11/site-packages/torchgating/run.py", line 168, in main
    assert not opt.cpu or torch.cuda.is_available() 
``` 

The problem is at line 168 in torchgating/run.py:

`assert not opt.cpu or torch.cuda.is_available()`

the line should be:

`assert  opt.cpu or torch.cuda.is_available()`

**Comment by nuniz** [comment]
Thank you; I've resolved this. Can you please check if this works for you?

**Comment by tpoindex** [comment]
Yes, works.  Thanks.
